

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.conversor;

import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Conversor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Conversor.class.getName());

    /**
     * Creates new form Conversor
     */
    public Conversor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BotaoLimpar = new javax.swing.JButton();
        BotaoConverter = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CampoResultado = new javax.swing.JTextField();
        BoxMoeda = new javax.swing.JComboBox<>();
        CampoValor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(700, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html><u>CONVERSOR DE MOEDAS</u></html>");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 460, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RESULTADO");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 70, 20));

        BotaoLimpar.setText("LIMPAR");
        BotaoLimpar.addActionListener(this::BotaoLimparActionPerformed);
        jPanel4.add(BotaoLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        BotaoConverter.setText("CONVERTER");
        BotaoConverter.addActionListener(this::BotaoConverterActionPerformed);
        jPanel4.add(BotaoConverter, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 400, 50));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INSIRA UM VALOR PARA CONVERTER");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, 20));

        CampoResultado.addActionListener(this::CampoResultadoActionPerformed);
        jPanel4.add(CampoResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 330, 40));

        BoxMoeda.setBackground(new java.awt.Color(255, 255, 255));
        BoxMoeda.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BoxMoeda.setForeground(new java.awt.Color(51, 51, 255));
        BoxMoeda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOLAR", "EURO", "IENE", "PESO ARGENTINO" }));
        BoxMoeda.addActionListener(this::BoxMoedaActionPerformed);
        jPanel4.add(BoxMoeda, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 100, 40));

        CampoValor.addActionListener(this::CampoValorActionPerformed);
        jPanel4.add(CampoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 330, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Documentos\\NetBeansProjects\\FlyWareTech\\src\\br\\edu\\conversor\\brasil.png")); // NOI18N
        jLabel1.setText("BRL");
        jPanel3.add(jLabel1);

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 100, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 500, 400));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparActionPerformed
        // TODO add your handling code here:
        CampoValor.setText("");
    }//GEN-LAST:event_BotaoLimparActionPerformed

    private void CampoResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoResultadoActionPerformed

    private void CampoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoValorActionPerformed

    private void BoxMoedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxMoedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxMoedaActionPerformed

    private void BotaoConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConverterActionPerformed
        // TODO add your handling code here:
        double reais,dolar,euro,iene,peso;
        
        try {
        
            String BoxV = (String) BoxMoeda.getSelectedItem();
            if (BoxV.equals("DOLAR")) {
            dolar = Double.parseDouble(CampoValor.getText());
            reais = (dolar * 5.7);
            
            CampoResultado.setText(String.valueOf(reais));
            }
            
        } 
        catch (NumberFormatException e) {
        CampoResultado.setText("Valor inválido");
        }

    }//GEN-LAST:event_BotaoConverterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Conversor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoConverter;
    private javax.swing.JButton BotaoLimpar;
    private javax.swing.JComboBox<String> BoxMoeda;
    private javax.swing.JTextField CampoResultado;
    private javax.swing.JTextField CampoValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
